"""add audit_logs and deletion_requests tables

Revision ID: 600f458cb0aa
Revises: dcbeadf04b11
Create Date: 2026-07-18 20:43:28.152575

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "600f458cb0aa"
down_revision: Union[str, Sequence[str], None] = "dcbeadf04b11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            name="fk_audit_log_execution_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_execution_action",
        "audit_logs",
        ["execution_id", "action"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_table(
        "deletion_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("requested_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=50),
            server_default="pending",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            name="fk_audit_log_execution_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "execution_id",
            name="uq_deletion_request_execution_id",
        ),
    )
    op.create_index(
        "idx_deletion_request_status_pending",
        "deletion_requests",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status > 'pending'"),
    )
    op.alter_column(
        "event_schema_version",
        "id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.drop_index(
        op.f("idx_execution_status_created"),
        table_name="executions",
    )
    op.create_index(
        "idx_execution_status_created",
        "executions",
        ["status", "created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_execution_status_created",
        table_name="executions",
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        op.f("idx_execution_status_created"),
        "executions",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "event_schema_version", "id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_index(
        "idx_deletion_request_status_pending",
        table_name="deletion_requests",
        postgresql_where=sa.text("status > 'pending'"),
    )
    op.drop_table("deletion_requests")
    op.drop_index(
        "idx_audit_execution_action",
        table_name="audit_logs",
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
