"""initial migrations

Revision ID: 74188398b504
Revises:
Create Date: 2026-05-24 16:23:55.203206

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "74188398b504"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING", "COMPLETED", "FAILED", name="execution_status_enum_types"
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "initial_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_execution_agent_id",
        "executions",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        "idx_execution_created_at",
        "executions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_execution_status",
        "executions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "checkpoints",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            name="fk_checkpoint_execution_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("execution_id", name="uq_checkpoint_execution_id"),
    )
    op.create_index(
        "idx_checkpoint_execution_id",
        "checkpoints",
        ["execution_id"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("step_name", sa.String(length=255), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "side_effects", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "STARTED",
                "COMPLETED",
                "FAILED",
                name="event_execution_status_enum_type",
            ),
            nullable=False,
        ),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            name="fk_event_execution_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "execution_id",
            "step_number",
            name="uq_event_execution_id_step_number",
        ),
    )
    op.create_index(
        "idx_event_created_at",
        "events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "idx_event_execution_id",
        "events",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        "idx_event_status",
        "events",
        ["status"],
        unique=False,
    )
    op.create_index(
        "idx_event_step_number",
        "events",
        ["execution_id", "step_number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_event_step_number", table_name="events")
    op.drop_index("idx_event_status", table_name="events")
    op.drop_index("idx_event_execution_id", table_name="events")
    op.drop_index("idx_event_created_at", table_name="events")
    op.drop_table("events")
    op.drop_index("idx_checkpoint_execution_id", table_name="checkpoints")
    op.drop_table("checkpoints")
    op.drop_index("idx_execution_status", table_name="executions")
    op.drop_index("idx_execution_created_at", table_name="executions")
    op.drop_index("idx_execution_agent_id", table_name="executions")
    op.drop_table("executions")
    op.execute("DROP TYPE IF EXISTS event_execution_status_enum_type")
    op.execute("DROP TYPE IF EXISTS execution_status_enum_types")
    # ### end Alembic commands ###
