"""rename agent_id to workflow_id in executions table

Revision ID: 776e016a012d
Revises: 600f458cb0aa
Create Date: 2026-07-19 21:44:55.290822

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "776e016a012d"
down_revision: Union[str, Sequence[str], None] = "600f458cb0aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "executions",
        sa.Column(
            "workflow_id",
            sa.String(length=255),
            nullable=True,
        ),
    )
    op.execute("UPDATE executions SET workflow_id = agent_id")
    op.alter_column(
        "executions",
        "workflow_id",
        nullable=False,
    )
    op.drop_index(
        op.f("idx_execution_agent_id"),
        table_name="executions",
    )
    op.drop_index(
        op.f("idx_execution_status_created"),
        table_name="executions",
    )
    op.create_index(
        "idx_execution_status_created",
        "executions",
        ["status", "created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        "idx_execution_workflow_id",
        "executions",
        ["workflow_id"],
        unique=False,
    )
    op.drop_column("executions", "agent_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "executions",
        sa.Column(
            "agent_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("idx_execution_workflow_id", table_name="executions")
    op.drop_index(
        "idx_execution_status_created",
        table_name="executions",
        postgresql_ops={"created_at": "DESC"},
    )
    op.create_index(
        op.f("idx_execution_status_created"),
        "executions",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("idx_execution_agent_id"),
        "executions",
        ["agent_id"],
        unique=False,
    )
    op.drop_column("executions", "workflow_id")
    # ### end Alembic commands ###
