"""add event_schema_version and state_metadata table, extend events table

Revision ID: dcbeadf04b11
Revises: 74188398b504
Create Date: 2026-07-15 02:23:20.317547

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from uuid_utils import uuid7

# revision identifiers, used by Alembic.
revision: str = "dcbeadf04b11"
down_revision: Union[str, Sequence[str], None] = "74188398b504"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    event_schema_version_table = op.create_table(
        "event_schema_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "schema_definition",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deprecated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("version"),
    )
    op.bulk_insert(
        event_schema_version_table,
        rows=[
            {
                "id": uuid7(),
                "version": 1,
                "description": "Phase 1 — Original schema",
            },
            {
                "id": uuid7(),
                "version": 2,
                "description": "Phase 2 — compression metadata + schema versioning",
            },
        ],
    )
    op.create_table(
        "state_metadata",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("compression_algorithm", sa.String(length=50), nullable=False),
        sa.Column("original_size_bytes", sa.Integer(), nullable=False),
        sa.Column("compressed_size_bytes", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["execution_id"],
            ["executions.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schema_version"],
            ["event_schema_version.version"],
        ),
        sa.PrimaryKeyConstraint("execution_id"),
    )
    op.add_column(
        "events",
        sa.Column(
            "schema_version",
            sa.Integer(),
            nullable=True,
            insert_default=1,
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "state_size_original_bytes",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "state_size_compressed_bytes",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "compression_algorithm",
            sa.String(length=50),
            nullable=True,
        ),
    )
    op.create_index(
        "idx_event_compression",
        "events",
        ["compression_algorithm"],
        unique=False,
    )
    op.create_index(
        "idx_event_execution_step_cover",
        "events",
        ["execution_id", "step_number"],
        unique=False,
        postgresql_include=["status", "cached", "duration_ms"],
    )
    op.create_index(
        "idx_event_schema_version",
        "events",
        ["schema_version"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_event_schema_version",
        "events",
        "event_schema_version",
        ["schema_version"],
        ["version"],
        ondelete="CASCADE",
    )
    op.add_column(
        "executions",
        sa.Column(
            "execution_mode",
            sa.String(length=50),
            nullable=False,
            insert_default="standard",
        ),
    )
    op.add_column(
        "executions",
        sa.Column(
            "deleted_at",
            sa.DateTime(),
            nullable=True,
        ),
    )
    op.create_index(
        "idx_execution_deleted_at",
        "executions",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        "idx_execution_status_created",
        "executions",
        ["status", "created_at"],
        unique=False,
        postgresql_ops={"created_at": "DESC"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_execution_status_created",
        table_name="executions",
        postgresql_ops={"created_at": "DESC"},
    )
    op.drop_index("idx_execution_deleted_at", table_name="executions")
    op.drop_column("executions", "deleted_at")
    op.drop_column("executions", "execution_mode")
    op.drop_constraint("fk_event_schema_version", "events", type_="foreignkey")
    op.drop_index("idx_event_schema_version", table_name="events")
    op.drop_index(
        "idx_event_execution_step_cover",
        table_name="events",
        postgresql_include=["status", "cached", "duration_ms"],
    )
    op.drop_index("idx_event_compression", table_name="events")
    op.drop_column("events", "compression_algorithm")
    op.drop_column("events", "state_size_compressed_bytes")
    op.drop_column("events", "state_size_original_bytes")
    op.drop_column("events", "schema_version")
    op.drop_table("state_metadata")
    op.drop_table("event_schema_version")
    # ### end Alembic commands ###
